In [1]:
import fasttext

In [2]:
model = fasttext.train_unsupervised('data/fil9', model='skipgram', dim=300, thread=8)
model.save_model("save_model/baseline/model_ssig.bin")

model.save_model("saved_model/baseline/model_skipgram.bin")

In [1]:
from common.preprocessing import *

In [6]:
model = fasttext.load_model("save_model/baseline/model_skipgram.bin")

In [4]:
baseline_W_in = model.get_input_matrix()

In [6]:
baseline_W_in.shape

(2218316, 300)

In [7]:
baseline_W_in[0]

array([ 7.92627990e-01,  5.31337298e-02,  1.33952165e+00,  1.61157811e+00,
        1.02158576e-01, -6.74681515e-02, -6.56054258e-01, -1.03927992e-01,
        9.60534334e-01,  1.87604502e-02, -3.23217720e-01,  6.66164637e-01,
        9.64844644e-01, -8.73652160e-01,  5.19923806e-01,  1.19330980e-01,
       -7.35771418e-01, -4.60181415e-01, -1.89034969e-01,  7.86002040e-01,
       -6.37846589e-01, -6.17170483e-02, -4.96022969e-01,  7.57560670e-01,
        2.47539327e-01, -3.64919156e-01, -4.52107430e-01, -2.97376253e-02,
        5.91966629e-01,  1.39670763e-02,  3.80145252e-01, -1.69083488e+00,
        2.68353730e-01, -6.66656792e-02,  6.81880176e-01, -9.13940489e-01,
       -1.10299706e+00,  9.71990287e-01, -3.75165820e-01, -6.11895204e-01,
        4.77920443e-01,  5.12814999e-01, -1.44678295e-01, -9.75686759e-02,
        9.62858140e-01, -1.23740292e+00, -3.25586468e-01,  3.53724211e-01,
       -8.55712742e-02, -6.95167303e-01,  3.60295512e-02,  2.55487263e-01,
       -7.26334095e-01, -

In [6]:
baseline_W_out = model_sg.get_output_matrix()
baseline_W_out.shape

(218316, 300)

In [8]:
model_sg.get_word_id('the')

0

In [24]:
model_sg.get_subword_id('the')

1080296

In [9]:
model.get_word_id("the")

0

In [5]:
import pickle 
with open('data/vocab.pkl', 'rb') as fr:
    _, word_to_id, id_to_word = pickle.load(fr)

In [6]:
import numpy as np

In [8]:
w_in = []
for id in range(len(id_to_word)):
    w_in.append(model.get_word_vector(id_to_word[id]).tolist())

w_in = np.array(w_in)

In [9]:
w_in.shape

(218316, 300)

In [10]:
with open('save_model/baseline/ssig_w_in.pkl', 'wb') as fw:
    pickle.dump(w_in, fw)

In [15]:
model.get_subwords('the')

(['the', '<th', '<the', '<the>', 'the', 'the>', 'he>'],
 array([      0, 1369467,  628042, 1867276, 1080296,  279250, 1034596]))

In [13]:
model.get_line('data/questions-words.txt')

(['data/questions-words.txt', '</s>'], [])

In [16]:
A = np.sum(baseline_W_in[model.get_subwords('the')[1]], axis=0)/7
A

array([-0.21269342, -0.0884036 ,  0.27730155, -0.04676437,  0.14040682,
       -0.161546  , -0.14262646, -0.03805006,  0.18231246, -0.17337212,
       -0.38583496, -0.12758376,  0.30474395,  0.1627169 , -0.04170211,
        0.09054831, -0.25100484,  0.06314964,  0.10289086,  0.32745498,
       -0.20147239,  0.04889358, -0.0313029 , -0.00696407, -0.07261524,
       -0.1197992 , -0.0335944 ,  0.0616868 ,  0.23685923,  0.16254556,
        0.03922842, -0.12375794, -0.16542831, -0.07546695, -0.01338917,
       -0.25413078, -0.23520018,  0.14715211, -0.14803502, -0.01862151,
       -0.12655692,  0.14259021, -0.04765189,  0.03494889,  0.05574936,
       -0.01406876,  0.01959141,  0.0203576 ,  0.19635381,  0.01301613,
        0.04854858, -0.30132845,  0.21582007, -0.13570854,  0.25461456,
       -0.1118265 , -0.16851231,  0.10856833,  0.06446725,  0.14712158,
        0.08796386,  0.00755777,  0.0650911 ,  0.14223476, -0.02733506,
       -0.25232372, -0.15584849,  0.20493011,  0.02771457, -0.06

In [17]:
subword_ids = get_subword_ids('the')
subword_ids

array([      0, 1369467,  628042, 1867276, 1080296,  279250, 1034596])

In [11]:
import numpy as np
subword_ids = get_subword_ids('the')  # common.preprocessing
vec = np.sum(baseline_W_in[subword_ids], axis=0)
vec /= len(subword_ids)

In [7]:
model_sg.get_word_vector('the')

array([-1.94238171e-01, -3.38013433e-02,  8.57507363e-02, -8.61072466e-02,
       -2.00130641e-01, -9.04240832e-02, -1.66761801e-01,  2.45423764e-01,
        1.14865609e-01, -1.40809357e-01,  4.11967412e-02, -3.09305601e-02,
        2.41306931e-01,  2.31786296e-02, -3.81190553e-02,  9.94733348e-02,
        3.63902710e-02, -1.50047451e-01,  1.04491085e-01,  1.28460556e-01,
        3.85578051e-02, -1.38503325e-03,  5.39482683e-02, -3.14456895e-02,
        7.02158660e-02, -2.79828489e-01,  1.15236817e-02,  1.68387052e-02,
        7.79143861e-03,  2.26570010e-01,  3.15994886e-03,  3.05218957e-02,
       -1.58676580e-01, -7.57000446e-02,  1.12372369e-01, -2.38835186e-01,
       -2.05650985e-01, -1.11456648e-01, -2.13073026e-02,  2.15381403e-02,
        5.22734458e-03, -5.92681346e-03,  1.39855489e-01, -3.64354923e-02,
       -9.90359411e-02, -1.72195360e-01,  1.78733140e-01, -1.81977287e-01,
       -1.51795730e-01,  2.35076874e-01, -1.07485972e-01, -1.99383330e-02,
       -1.03649691e-01,  

In [7]:
lines = make_corpus('data/fil9')
vocab = make_vocab(lines, 5)
word_to_id, id_to_word = make_vocab_map(model_sg.words)

In [8]:
import pickle
with open('data/vocab.pkl', 'wb') as fw:
    pickle.dump((vocab, word_to_id, id_to_word), fw)

In [11]:
print(len(vocab))
print(model_sg.get_input_matrix().shape)

218316
(2218316, 300)


In [30]:
import pickle
weight_file = 'train_log/ssig_5epoch/weight/ssig_5epoch.pkl'
with open(weight_file, 'rb') as fr:
    W_in, W_hash_in, _ = pickle.load(fr)

In [31]:
import numpy as np
from common.preprocessing import get_subword_ids

w_in = []
for id in range(len(id_to_word)):
    subword_ids = get_subword_ids(id_to_word[id])
    vec = np.sum(W_hash_in[subword_ids], axis=0)
    vec /= len(subword_ids)
    w_in.append(vec.tolist())
w_in = np.array(w_in)



In [19]:
w_in.shape

(218316, 300)

In [33]:
W_in[0]

array([-1.72387049e-01,  3.72523159e-01, -4.81666848e-02, -9.25840512e-02,
        2.85371989e-01,  7.51389414e-02,  1.71957359e-01,  1.47785529e-01,
       -5.22937894e-01, -1.03976883e-01, -2.25675553e-01,  7.12687243e-03,
        2.47481272e-01, -1.21973671e-01, -2.57331640e-01, -2.60612100e-01,
        6.07084893e-02, -9.30427164e-02,  1.66051760e-01, -1.31332010e-01,
       -1.10613890e-01,  2.49117538e-01,  4.25686613e-02,  6.96115643e-02,
        2.93759972e-01,  4.35927063e-01, -1.24651566e-01, -1.68896228e-01,
       -1.72272295e-01, -5.34005165e-02,  5.08080162e-02,  3.81486565e-01,
       -5.68543077e-02,  2.41604775e-01, -3.46048743e-01, -2.61722356e-01,
       -6.25696838e-01, -3.33719105e-01, -5.13128899e-02,  1.04658650e-02,
       -4.68376219e-01,  4.73905087e-01, -1.84571311e-01,  1.80073813e-01,
       -5.86502962e-02, -5.02789915e-02, -1.80568606e-01, -3.59098390e-02,
       -4.11543064e-02,  2.89351135e-01, -4.21686560e-01,  2.96759438e-02,
       -6.95016235e-02, -

In [32]:
w_in[0]

array([-1.73548073e-01,  3.45749795e-01, -7.95686468e-02, -1.03670515e-01,
        2.75454432e-01,  6.89055845e-02,  1.98918790e-01,  1.33202747e-01,
       -5.11099458e-01, -1.00448310e-01, -2.27782771e-01,  1.75596513e-02,
        2.35871240e-01, -1.23313449e-01, -2.79708654e-01, -2.62493521e-01,
        4.79822829e-02, -6.10803701e-02,  1.64012328e-01, -1.46916300e-01,
       -1.13318406e-01,  2.47825652e-01,  4.89481576e-02,  6.17243834e-02,
        2.91347951e-01,  4.52758461e-01, -1.35424837e-01, -1.62182212e-01,
       -1.73629180e-01, -5.18827438e-02,  4.55761850e-02,  3.95994842e-01,
       -5.41988611e-02,  2.59958059e-01, -3.40617448e-01, -2.52138823e-01,
       -6.33744657e-01, -3.49288464e-01, -4.39985804e-02, -1.10512762e-03,
       -4.54560101e-01,  4.71226692e-01, -1.75855324e-01,  1.76728889e-01,
       -7.39756897e-02, -3.40421088e-02, -1.78753570e-01, -5.98036721e-02,
       -3.46152522e-02,  2.83671856e-01, -4.32958663e-01,  4.26976942e-02,
       -6.50515407e-02, -

In [29]:
subword_ids = get_subword_ids('the')
print(subword_ids)
np.sum(W_hash_in[subword_ids], axis=0)/len(subword_ids)

[      0 1369467  628042 1867276 1080296  279250 1034596]


array([ 7.52436519e-02, -2.87516028e-01, -2.27820963e-01,  5.74163981e-02,
        5.75493813e-01, -1.83224916e-01,  3.03775042e-01,  2.00321510e-01,
        2.28116438e-01, -4.77823198e-01, -3.27535346e-02, -2.55350769e-01,
       -4.08618271e-01, -1.77582726e-01,  1.62636548e-01,  3.70556712e-02,
       -4.00994927e-01,  1.38716742e-01, -1.47095054e-01, -1.36492088e-01,
       -4.77526844e-01, -2.12789878e-01, -8.88833255e-02,  7.70400232e-03,
        3.28798831e-01,  3.29714924e-01, -1.32507235e-02, -2.11945847e-01,
        2.52255172e-01,  2.66626269e-01, -3.21746528e-01,  1.99330166e-01,
       -2.56259024e-01,  3.58082086e-01, -6.35325909e-01, -7.03929842e-01,
       -1.85757264e-01, -1.45267367e-01, -7.06595182e-02, -2.11153999e-01,
       -4.45933610e-01,  2.63424307e-01,  3.98057401e-01,  1.47991389e-01,
        1.34846300e-01,  1.69595584e-01,  2.81931847e-01,  2.63235748e-01,
        5.19539773e-01, -4.00585607e-02, -8.95115286e-02, -3.36018771e-01,
       -2.28578806e-01,  

In [ ]:
from common.functions import unigramsampler

negative_num=5
contexts = [ 5, 10, 3134, 1230, 42, 21]

sample_table = []
sample_table = unigramsampler(vocab, word_to_id, power=3/4)
sample_table = np.array(sample_table)

while True:
    b = np.random.randint(low=0, high=len(sample_table), size=(negative_num * len(contexts)))
    if len(np.intersect1d(sample_table[b], np.array(contexts)).tolist()) == 0:  # 교집합이 있는지 확인
        neg_samples = sample_table[b]
        break