In [5]:
import numpy as np
W_hash_in = 0.1 * np.random.randn(10, 5).astype('f')
print(W_hash_in)
W_out = 0.1 * np.random.randn(10, 5).astype('f')
print(W_out)

[[ 0.14407812  0.0500376   0.08961784 -0.06179884  0.0528465 ]
 [-0.05985213 -0.07301822 -0.2635567   0.13362764  0.13176589]
 [ 0.12214801  0.03756325 -0.06553881 -0.06963905 -0.06832203]
 [-0.00487475  0.22527556  0.0633746  -0.32199037  0.10652103]
 [ 0.19587426  0.11883654 -0.2801226  -0.09892868 -0.13672052]
 [-0.03663511  0.17184521  0.0555879   0.0423632  -0.02266259]
 [-0.0746548   0.03135461 -0.01216353 -0.17437991  0.04069547]
 [ 0.134538   -0.14594361 -0.18757589 -0.21654765  0.03577449]
 [-0.06318529  0.11427727  0.13370085  0.07990576 -0.07427066]
 [ 0.01233653 -0.04456625  0.04197911  0.03316524  0.03579945]]
[[ 0.09769375 -0.01186548  0.0033195  -0.02564826 -0.01049338]
 [ 0.11653662  0.02318947  0.08592043  0.11370049 -0.01759648]
 [-0.09300634 -0.12630832 -0.10996639  0.00312427 -0.13661304]
 [ 0.10492289 -0.17034495 -0.12499949 -0.11208407 -0.0612913 ]
 [-0.17773096 -0.07733493  0.04897014  0.04825225 -0.15271345]
 [ 0.09327556  0.01915945  0.06744102  0.17260742 -0.1

In [13]:
A = [7, 2, 9]
B = [[1, 3, 8, 5], [4, 6, 0, 3]]
h = np.sum(W_hash_in[np.array(A)], axis=0)/3
w_out = W_out[np.array(B)]
print(h)
print(w_out.transpose(0, 2, 1))

[ 0.08967417 -0.0509822  -0.07037853 -0.08434048  0.00108397]
[[[ 0.11653662  0.10492289  0.10709582  0.09327556]
  [ 0.02318947 -0.17034495  0.15477984  0.01915945]
  [ 0.08592043 -0.12499949  0.0096229   0.06744102]
  [ 0.11370049 -0.11208407 -0.21641926  0.17260742]
  [-0.01759648 -0.0612913  -0.00660645 -0.12908189]]

 [[-0.17773096 -0.12168542  0.09769375  0.10492289]
  [-0.07733493  0.03217422 -0.01186548 -0.17034495]
  [ 0.04897014  0.0290304   0.0033195  -0.12499949]
  [ 0.04825225 -0.19924816 -0.02564826 -0.11208407]
  [-0.15271345 -0.00189871 -0.01049338 -0.0612913 ]]]


In [15]:
out = np.dot(h, w_out.transpose(0, 2, 1))
out

array([[-0.00638751,  0.0362775 ,  0.01928121, -0.0120565 ],
       [-0.01967677,  0.00220716,  0.01128372,  0.0362775 ]],
      dtype=float32)

In [3]:
def sigmoid(x):
    out = 1 / (1 + np.exp(-x))
    return out

In [19]:
out = sigmoid(out)
print(out)

[[0.62208396 0.6245881  0.6235914  0.6217508 ]
 [0.6213026  0.62258893 0.623122   0.6245881 ]]


In [29]:
p_loss = -np.sum(np.log(out[:, :1] + 1e-07))
print(p_loss)
n_loss = -np.sum(np.log(1 - out[:, 1:] + 1e-07))
print(n_loss)
loss = p_loss + n_loss
print(loss)

0.95061684
5.8589973
6.809614


In [32]:
dout = out.copy()
print(dout)
dout[:,:1] -= 1
print(dout)

[[0.62208396 0.6245881  0.6235914  0.6217508 ]
 [0.6213026  0.62258893 0.623122   0.6245881 ]]
[[-0.37791604  0.6245881   0.6235914   0.6217508 ]
 [-0.3786974   0.62258893  0.623122    0.6245881 ]]


In [42]:
import pickle

dictionary_pkl = 'data/vocab.pkl'
with open(dictionary_pkl, 'rb') as fr:
    vocab, word_to_id, id_to_word = pickle.load(fr)
    fr.close()

word_p = np.array(list(vocab.values()))

In [43]:
word_p

array([7446708, 4453926, 3776770, ...,       5,       5,       5])

In [53]:
grads = [np.zeros_like(W_out)]
dW, = grads
dW[...] = 0

ValueError: array is not broadcastable to correct shape

In [ ]:
class Embedding:
    def __init__(self, W):
        self.params = [W]
        self.grads = [np.zeros_like(W)]
        self.idx = None
    
    def forward(self, idx):
        W, = self.params
        self.idx = idx
        out = W[idx]
        return out

    def backward(self, dout):
        dW, = self.grads
        dW[...] = 0
        np.add.at(dW, self.idx, dout)
        return None

In [4]:
from common.functions import make_contexts

temp_corpus = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
idx = 9
window = 4

contexts = make_contexts(window, temp_corpus, idx)
print(contexts)

[6, 7, 8, 10]
